spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog_1?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: garbohsing
    type: com.alibaba.druid.pool.DruidDataSource
  profiles:
    active: dev

mybatis-plus:
  type-aliases-package: com.garbo.entity
  mapper-locations: classpath*:/mapper/**Mapper.xml
  global-config:
    db-config:
      logic-not-delete-value: 0
      logic-delete-value: 1
      logic-delete-field: flag
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

